services:

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infra/init-db.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  mlflow:
    build:
      context: .
      dockerfile: infra/Dockerfile.mlflow
    ports:
      - "5000:5000"
    volumes:
      - ./mlflow_artifacts:/home/guest/tools/Fake-Job-Postings-Detector/mlflow_artifacts
    command: >
      mlflow server
      --backend-store-uri postgresql://airflow:airflow@postgres/mlflow
      --default-artifact-root /home/guest/tools/Fake-Job-Postings-Detector/mlflow_artifacts
      --host 0.0.0.0
      --allowed-hosts "*"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 10s
      retries: 5

  # mlflow_model:
  #   build:
  #     context: .
  #     dockerfile: infra/Dockerfile.mlflow
  #   ports:
  #     - "5001:5001"
  #   environment:
  #     MLFLOW_TRACKING_URI: http://mlflow:5000
  #   volumes:
  #     - ./mlflow_artifacts:/home/guest/tools/Fake-Job-Postings-Detector/mlflow_artifacts  # ✅ ADD THIS
  #   command: >
  #     mlflow models serve
  #     -m models:/first_model@production
  #     --host 0.0.0.0
  #     --port 5001
  #     --env-manager=local
  #   depends_on:
  #     mlflow:
  #       condition: service_healthy
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
  #     interval: 10s
  #     retries: 5

  api:
    build:
      context: .
      dockerfile: infra/Dockerfile
    ports:
      - "8000:8000"
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000
      MODEL_SERVE_MODE: ${MODEL_SERVE_MODE:-local}
      MLFLOW_SERVE_URL: ${MLFLOW_SERVE_URL:-http://mlflow_model:5001/invocations}
    volumes:
      - ./data:/app/data
      - ./data/baselines:/app/baselines
    depends_on:
      mlflow:
        condition: service_healthy
      # mlflow_model:
        # condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      retries: 3
    

  airflow:
    build:
      context: .
      dockerfile: infra/Dockerfile.airflow
    ports:
      - "8080:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./src:/opt/airflow/src
      - ./.dvc:/opt/airflow/.dvc          # DVC config
      - ./.git:/opt/airflow/.git          # Git repo
      - ./dvc.yaml:/opt/airflow/dvc.yaml  # DVC pipeline
      - ./dvc.lock:/opt/airflow/dvc.lock  # DVC lock
      - ./scripts:/opt/airflow/scripts    # Pipeline scripts
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW_FERNET_KEY}
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__API__SECRET_KEY: ${AIRFLOW_SECRET_KEY}
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "True"
      _AIRFLOW_WWW_USER_USERNAME: airflow
      _AIRFLOW_WWW_USER_PASSWORD: airflow
      MLFLOW_TRACKING_URI: http://mlflow:5000
      AIRFLOW__SMTP__SMTP_HOST: ${SMTP_HOST}
      AIRFLOW__SMTP__SMTP_PORT: ${SMTP_PORT}
      AIRFLOW__SMTP__SMTP_USER: ${SMTP_USER}
      AIRFLOW__SMTP__SMTP_PASSWORD: ${SMTP_PASSWORD}
      AIRFLOW__SMTP__SMTP_MAIL_FROM: ${SMTP_FROM}
      AIRFLOW__SMTP__SMTP_SSL: "False"
      AIRFLOW__SMTP__SMTP_STARTTLS: "True"
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      bash -c "airflow db init &&
              sleep 5 &&
              airflow users create --username admin --password admin
              --firstname Admin --lastname User --role Admin
              --email admin@example.com || true &&
              airflow webserver & airflow scheduler"

  alertmanager:
    image: prom/alertmanager:latest
    ports:
      - "9093:9093"
    volumes:
      - ./monitoring/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
    # environment:
    #   ALERT_FROM_EMAIL: ${ALERT_FROM_EMAIL}
    #   GMAIL_APP_PASSWORD: ${GMAIL_APP_PASSWORD}
    #   ALERT_TO_EMAIL: ${ALERT_TO_EMAIL}

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./monitoring/alert_rules.yml:/etc/prometheus/alert_rules.yml
    depends_on:
      - api
      - alertmanager

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
      # GF_SMTP_ENABLED: "true"
      # GF_SMTP_HOST: "smtp.gmail.com:587"
      # GF_SMTP_USER: ${ALERT_FROM_EMAIL}
      # GF_SMTP_PASSWORD: ${GMAIL_APP_PASSWORD}

volumes:
  postgres_data:
  mlflow_data:
  grafana_data: