services:
  web:
    container_name: web-app
    build: 
        context: .
        dockerfile: infra/Dockerfile
    ports:
      - "${APP_PORT}:5000"
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}

  redis:
    container_name: redis-server
    image: redis:alpine