FROM apache/airflow:latest

USER root

# Install system dependencies (if needed later)
RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    && rm -rf /var/lib/apt/lists/*

USER airflow

# Install Python dependencies for DAGs
COPY requirements-airflow.txt .

RUN pip install --no-cache-dir -r requirements-airflow.txt