FROM apache/airflow:2.9.2-python3.11

USER root

# Install system dependencies (if needed later)
RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y git

USER airflow

# Install Python dependencies for DAGs
COPY requirements-airflow.txt .

RUN pip install --no-cache-dir -r requirements-airflow.txt